"""add slug to session

Revision ID: 50c5da35f496
Revises: 71f8e48123c4
Create Date: 2025-08-29 14:21:18.582941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c5da35f496'
down_revision = '71f8e48123c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_chat_sessions_slug'), 'chat_sessions', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_slug'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'slug')
    # ### end Alembic commands ###