"""Add status and follow_up_question to chat_messages

Revision ID: c88638c28854
Revises: a8b9c1d2e3f4
Create Date: 2025-12-19 14:00:47.116573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88638c28854'
down_revision = 'a8b9c1d2e3f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('chat_messages', sa.Column('follow_up_question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'follow_up_question')
    op.drop_column('chat_messages', 'status')
    # ### end Alembic commands ###